### ISSUE TITLE
bug at re-opnening index.html

### ISSUE THREAD

**Issue by thierry-carron** [Pingendo/pingendo#21]
Hi,
I worked yesterday on my index.html file, saved my work before to close and quit pingendo.
This morning I started the app and opened this file again, as other days.
but the content is totally virgin / blank:

everything erased.
is there any cache somewhere to reload past version ?
any help ?

**Comment by gseregni** [comment]
So bad. No, pingendo does not keep caches of files. 
Do you edited the index with other files while working ? or did you work with pingendo only?

**Comment by gseregni** [comment]
We'll investigate further, in any case would be safer to keep a cache of working files as you seggested.

**Comment by thierry-carron** [comment]
i used no other text editor to open the file at the same time. I remembered to press ctrl+S before closing the index.html, then i quit by closing pingendo app.

I saved the pingendo folder in .zip into C:\Users\username\AppData\Roaming if you need it.

into log.lo fil
[2018-10-27 16:50:11.691] [info] Checking for update
[2018-10-27 16:50:30.256] [error] Error: Error: net::ERR_NAME_NOT_RESOLVED
    at t.CancellationToken.this [as createPromise] (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\builder-util-runtime\out\CancellationToken.js:89:1)
    at t.ElectronHttpExecutor.doApiRequest (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\builder-util-runtime\out\httpExecutor.js:151:10)
    at t.ElectronHttpExecutor.options (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\builder-util-runtime\out\httpExecutor.js:144:25)
    at t.GitHubProvider.this [as httpRequest] (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\providers\Provider.js:69:1)
    at C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\providers\GitHubProvider.js:107:1
    at Generator.next (<anonymous>)
From previous event:
    at t.GitHubProvider.options [as getLatestVersion] (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\providers\GitHubProvider.js:174:1)
    at C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:519:1
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.NsisUpdater.getUpdateInfo (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:519:1)
    at info (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:522:1)
    at Generator.next (<anonymous>)
From previous event:
    at t.NsisUpdater.asArray [as doCheckForUpdates] (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:548:68)
    at e (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:439:62)
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at t.NsisUpdater.requestHeaders [as _checkForUpdates] (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:448:1)
    at t.NsisUpdater.checkForUpdates (C:\Program Files\Pingendo\resources\app.asar\webpack:\node_modules\electron-updater\out\AppUpdater.js:358:1)
    at App.checkForUpdates (C:\Program Files\Pingendo\resources\app.asar\webpack:\src\main\update.js:15:15)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
[2018-10-27 19:16:45.313] [info] Checking for update
[2018-10-27 19:16:47.707] [info] Update for version 4.1.22 is not available (latest version: 4.1.22, downgrade is disallowed).
[2018-10-28 08:56:31.279] [info] Checking for update
[2018-10-28 08:56:33.571] [info] Update for version 4.1.22 is not available (latest version: 4.1.22, downgrade is disallowed).

**Comment by thierry-carron** [comment]
thank you for the quick update, seems ok now.
