### ISSUE TITLE
Installation issue regarding npm

### ISSUE THREAD

**Issue by yseen** [Pingendo/pingendo#23]
I installed Pingendo without first installing npm on a 32-bit Windows 7 computer. Nothing seemed to work in the program.

Looking under the ```Dev Tools > Console``` tab, I saw the following error located at C:\Program Files\Pingendo\resources\app.asar\node_modules\node-sass\lib\binding.js on line 15:

```Uncaught (in promise) Error: Missing binding C:\Program Files\Pingendo\resources\app.asar\node_modules\node-sass\vendor\win32-ia32-57\binding.node
Node Sass could not find a binding for your current environment: Windows 32-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x
  - OS X 64-bit with Node.js 10.x
  - Linux 64-bit with Node.js 8.x
  - Linux 64-bit with Node.js 10.x
  - Windows 64-bit with Node.js 8.x
  - Windows 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (C:\Program Files\Pingendo\resources\app.asar\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\Program Files\Pingendo\resources\app.asar\node_modules\node-sass\lib\index.js:14:35)
    at Object.<anonymous> (C:\Program Files\Pingendo\resources\app.asar\node_modules\node-sass\lib\index.js:477:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
```

I then installed node.js and npm. I ran ```npm install``` and ```npm rebuild node-sass``` from the command line.

I uninstalled Pingendo, deleted the ```user/AppData/Roaming/Pingendo``` folder, restarted the computer, and reinstalled Pingendo, but I still get the same error and the program is completely unusable.

**Comment by gseregni** [comment]
Version 4.1.26 solve an issue we had with 32bit windows sys.
